---
# Ansible Galaxy role dependencies

roles:
  # Common roles from Ansible Galaxy
  - name: geerlingguy.docker
    version: 6.1.0
  
  - name: geerlingguy.postgresql
    version: 3.4.0
  
  - name: geerlingguy.nginx
    version: 3.1.4
  
  - name: geerlingguy.nodejs
    version: 6.1.0

collections:
  # Ansible collections
  - name: community.general
    version: 7.0.0
  
  - name: ansible.posix
    version: 1.5.0
  
  - name: community.docker
    version: 3.4.0
  
  - name: community.postgresql
    version: 2.4.0
  
  - name: amazon.aws
    version: 6.0.0
  
  - name: google.cloud
    version: 1.2.0
  
  - name: azure.azcollection
    version: 1.16.0
