apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicenow-mock
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: servicenow-mock
  template:
    metadata:
      labels:
        app: servicenow-mock
    spec:
      containers:
      - name: servicenow-mock
        image: mendhak/http-https-echo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicenow-mock
  namespace: monitoring
spec:
  selector:
    app: servicenow-mock
  ports:
  - port: 80
    targetPort: 8080
